### ISSUE TITLE
Mail domain

### ISSUE THREAD

**Issue by MattiSG** [fix-macosx/yosemite-phone-home#3]
> Mail quietly sends the domain entered by the user to Apple, too.

This sounds legit, as this is how auto setup can be achieved for the most usual providers. It would be more appropriate to specify whether a unique ID is sent along with this request.

**Comment by landonf** [comment]
There's very little that a device can send that isn't trivially uniquely identifying. As far as supporting the usual providers, there's nothing that indicates that mail setup information will be silently shared with Apple, much less any sort of informed consent.
